# Wilhelm Lange
## Week12: 04/16/2026
### Python - Pandas DataFrame Processing

In [1]:
import numpy as np
import pandas as pd
from numpy.random import *
from pandas import *

In [2]:
#Drop Entries
df = DataFrame(np.arange(1,17).reshape((4,4)),
              columns=['one', 'two','three', 'four'],
              index=['Ohio', 'Colorado', 'Utah', 'New York'])
df

          one  two  three  four
Ohio        1    2      3     4
Colorado    5    6      7     8
Utah        9   10     11    12
New York   13   14     15    16

In [3]:
df.index

Index(['Ohio', 'Colorado', 'Utah', 'New York'], dtype='object')

In [4]:
df.index.name

In [5]:
df.drop(['Colorado'])

          one  two  three  four
Ohio        1    2      3     4
Utah        9   10     11    12
New York   13   14     15    16

In [6]:
df.drop(['Utah', 'Ohio'])

          one  two  three  four
Colorado    5    6      7     8
New York   13   14     15    16

In [7]:
df

          one  two  three  four
Ohio        1    2      3     4
Colorado    5    6      7     8
Utah        9   10     11    12
New York   13   14     15    16

In [8]:
df.drop(['three'], axis='columns')

          one  two  four
Ohio        1    2     4
Colorado    5    6     8
Utah        9   10    12
New York   13   14    16

In [9]:
df.drop(['three'], axis=1)

          one  two  four
Ohio        1    2     4
Colorado    5    6     8
Utah        9   10    12
New York   13   14    16

In [10]:
df.drop(['three', 'one'], axis=1)

          two  four
Ohio        2     4
Colorado    6     8
Utah       10    12
New York   14    16

In [11]:
df1 = df.copy()
df1

          one  two  three  four
Ohio        1    2      3     4
Colorado    5    6      7     8
Utah        9   10     11    12
New York   13   14     15    16

In [12]:
df.drop(['three', 'one'], axis=1, inplace=True)

In [13]:
df

          two  four
Ohio        2     4
Colorado    6     8
Utah       10    12
New York   14    16

In [14]:
df1[df1['three'] >= 7]

          one  two  three  four
Colorado    5    6      7     8
Utah        9   10     11    12
New York   13   14     15    16

In [16]:
# Data alignment
df1 = DataFrame(np.arange(9).reshape(3,3), columns=list('bcd'),
               index=['Ohio', 'Texas', 'Colorado'])

df2 = DataFrame(np.arange(12).reshape(4,3), columns=list('bde'),
               index=[ 'Utah','Ohio', 'Texas', 'Oregon'])

In [17]:
df1

          b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [18]:
df1 + df2

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [19]:
df1.add(df2)

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [20]:
df1

          b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [21]:
df2

        b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [23]:
df1.add(df2, fill_value=0) # number + 0 instead of (number + nan = nan)

            b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

In [24]:
df1['e'] = df1['b'] + df1['d']
df1

          b  c  d   e
Ohio      0  1  2   2
Texas     3  4  5   8
Colorado  6  7  8  14

In [27]:
#sort and rank
df = DataFrame(np.random.choice(np.arange(1,21), size=8).reshape(2,4),
              columns=list('dabd'),
              index=['three', 'one'])
df

        d   a   b   d
three  11  13  18   4
one     9  20  18  13

In [29]:
df.sort_index()

        d   a   b   d
one     9  20  18  13
three  11  13  18   4

In [30]:
df.sort_index(axis=1)

        a   b   d   d
three  13  18  11   4
one    20  18   9  13

In [31]:
df

        d   a   b   d
three  11  13  18   4
one     9  20  18  13

In [32]:
df.sort_index(axis=1, ascending=False)

        d   d   b   a
three  11   4  18  13
one     9  13  18  20

In [33]:
# Sort by values
df.sort_values(by='b')

        d   a   b   d
three  11  13  18   4
one     9  20  18  13

In [34]:
df.sort_values(by='d')

ValueError: The column label 'd' is not unique.

In [36]:
df = DataFrame(np.random.choice(np.arange(-10,20), size=16).reshape(4,4),
              columns=list('dabc'),
              index=['three', 'one', 'four', 'seven'])
df

        d   a   b   c
three   7  -3   8  16
one    -4  10  13  12
four   19  16  15  17
seven   7  -3  -3  14

In [37]:
df.sort_values(by='c')

        d   a   b   c
one    -4  10  13  12
seven   7  -3  -3  14
three   7  -3   8  16
four   19  16  15  17

In [38]:
df.sort_values(by=['a', 'd'])

        d   a   b   c
three   7  -3   8  16
seven   7  -3  -3  14
one    -4  10  13  12
four   19  16  15  17

In [ ]:
df.sort_values(by='seven', axis = 1)

In [39]:
df.sort_values(by=['one','seven'], axis = 1)

        d   a   c   b
three   7  -3  16   8
one    -4  10  12  13
four   19  16  17  15
seven   7  -3  14  -3

In [40]:
df.sort_values(by=['one','seven'], axis = 1, inplace=True)

In [41]:
df

        d   a   c   b
three   7  -3  16   8
one    -4  10  12  13
four   19  16  17  15
seven   7  -3  14  -3

In [42]:
# Ranking
df.rank()

         d    a    c    b
three  2.5  1.5  3.0  2.0
one    1.0  3.0  1.0  3.0
four   4.0  4.0  4.0  4.0
seven  2.5  1.5  2.0  1.0

In [43]:
df.rank().astype(int)

       d  a  c  b
three  2  1  3  2
one    1  3  1  3
four   4  4  4  4
seven  2  1  2  1

In [44]:
df.values

array([[ 7, -3, 16,  8],
       [-4, 10, 12, 13],
       [19, 16, 17, 15],
       [ 7, -3, 14, -3]])

In [45]:
# Statistics
df

        d   a   c   b
three   7  -3  16   8
one    -4  10  12  13
four   19  16  17  15
seven   7  -3  14  -3

In [47]:
df['e'] = np.where(df['a'] > 2, df['c'], np.nan)

In [48]:
df

        d   a   c   b     e
three   7  -3  16   8   NaN
one    -4  10  12  13  12.0
four   19  16  17  15  17.0
seven   7  -3  14  -3   NaN

In [49]:
df.sum()

d    29.0
a    20.0
c    59.0
b    33.0
e    29.0
dtype: float64

In [50]:
df.sum(axis=1)

three    28.0
one      43.0
four     84.0
seven    15.0
dtype: float64

In [51]:
df.mean()

d     7.25
a     5.00
c    14.75
b     8.25
e    14.50
dtype: float64

In [52]:
df.mean(axis='columns')

three     7.00
one       8.60
four     16.80
seven     3.75
dtype: float64

In [53]:
df.values

array([[ 7., -3., 16.,  8., nan],
       [-4., 10., 12., 13., 12.],
       [19., 16., 17., 15., 17.],
       [ 7., -3., 14., -3., nan]])

In [54]:
df.mean(axis=1, skipna=False)

three     NaN
one       8.6
four     16.8
seven     NaN
dtype: float64

In [55]:
df.min()

d    -4.0
a    -3.0
c    12.0
b    -3.0
e    12.0
dtype: float64

In [56]:
df.min(axis=1)

three    -3.0
one      -4.0
four     15.0
seven    -3.0
dtype: float64

In [57]:
df.max(axis=1)

three    16.0
one      13.0
four     19.0
seven    14.0
dtype: float64