# WIlhelm Lange
## Week 13 : 14/04/2026
### Python - Pandas Series and DataFrame

In [1]:
import numpy as np
from numpy.random import randn, random
import pandas as pd
from pandas import Series, DataFrame # * to import everything

In [5]:
# Panda Series: It is a one dimensional array holding data of any type
s = Series(randn(15) * 10)
s

0     -5.473493
1     10.320492
2     -7.145682
3    -10.975444
4      6.632955
5      1.985866
6     -9.319772
7      6.058962
8     10.920953
9     13.575546
10    -0.481171
11     5.185783
12    -3.013598
13    15.405260
14    -5.580095
dtype: float64

In [6]:
type(s)

pandas.core.series.Series

In [7]:
s.index

RangeIndex(start=0, stop=15, step=1)

In [8]:
s.values

array([ -5.47349328,  10.32049219,  -7.14568182, -10.97544423,
         6.63295505,   1.98586575,  -9.31977171,   6.05896242,
        10.9209528 ,  13.5755458 ,  -0.48117074,   5.18578344,
        -3.01359805,  15.4052596 ,  -5.58009499])

In [9]:
s[:3]

0    -5.473493
1    10.320492
2    -7.145682
dtype: float64

In [10]:
s[14]

-5.580094987089811

In [11]:
# Create Labels
s = Series(np.arange(10,15), index=['w','x','y','z','t'])
s

w    10
x    11
y    12
z    13
t    14
dtype: int32

In [12]:
s['w']

10

In [13]:
so = Series([2520,1122,937,847,713], index = ['USA', 'Russia', 'Germany', 'UK', 'France'])
so

USA        2520
Russia     1122
Germany     937
UK          847
France      713
dtype: int64

In [14]:
so['USA']

2520

In [15]:
so[so > 800]

USA        2520
Russia     1122
Germany     937
UK          847
dtype: int64

In [16]:
so > 800

USA         True
Russia      True
Germany     True
UK          True
France     False
dtype: bool

In [17]:
# Convert Series to dictionary
d = dict(so)
d

{'USA': 2520, 'Russia': 1122, 'Germany': 937, 'UK': 847, 'France': 713}

In [18]:
# Convert deictionary to series
s2 = Series(d)
s2

USA        2520
Russia     1122
Germany     937
UK          847
France      713
dtype: int64

In [20]:
# merge
country = ['Russia', 'France', 'Spain', 'Germany', 'USA', 'UK', 'Italy']
country

['Russia', 'France', 'Spain', 'Germany', 'USA', 'UK', 'Italy']

In [21]:
s2 = Series(d, index=country)
s2

Russia     1122.0
France      713.0
Spain         NaN
Germany     937.0
USA        2520.0
UK          847.0
Italy         NaN
dtype: float64

In [22]:
pd.isnull(s2)

Russia     False
France     False
Spain       True
Germany    False
USA        False
UK         False
Italy       True
dtype: bool

In [24]:
pd.notnull(s2)

Russia      True
France      True
Spain      False
Germany     True
USA         True
UK          True
Italy      False
dtype: bool

In [25]:
s2

Russia     1122.0
France      713.0
Spain         NaN
Germany     937.0
USA        2520.0
UK          847.0
Italy         NaN
dtype: float64

In [26]:
so + s2

France     1426.0
Germany    1874.0
Italy         NaN
Russia     2244.0
Spain         NaN
UK         1694.0
USA        5040.0
dtype: float64

In [27]:
s2

Russia     1122.0
France      713.0
Spain         NaN
Germany     937.0
USA        2520.0
UK          847.0
Italy         NaN
dtype: float64

In [28]:
s2.name = "Summer Olympic"
s2

Russia     1122.0
France      713.0
Spain         NaN
Germany     937.0
USA        2520.0
UK          847.0
Italy         NaN
Name: Summer Olympic, dtype: float64

In [29]:
s2.index.name = 'Country'
s2

Country
Russia     1122.0
France      713.0
Spain         NaN
Germany     937.0
USA        2520.0
UK          847.0
Italy         NaN
Name: Summer Olympic, dtype: float64

In [30]:
# DataFrame: is a 2 dimensional array
d = {
    "calories": [420, 380, 390],
    "fruits": ['Orange', 'Banana', 'Grape']
}
d

{'calories': [420, 380, 390], 'fruits': ['Orange', 'Banana', 'Grape']}

In [32]:
df = DataFrame(d)
df

   calories  fruits
0       420  Orange
1       380  Banana
2       390   Grape

In [33]:
df.describe()

         calories
count    3.000000
mean   396.666667
std     20.816660
min    380.000000
25%    385.000000
50%    390.000000
75%    405.000000
max    420.000000

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   calories  3 non-null      int64
 1   fruits    3 non-null      object
dtypes: int64(1), object(1)
memory usage: 176.0+ bytes

In [35]:
df['calories']

0    420
1    380
2    390
Name: calories, dtype: int64

In [36]:
df['fruits']

0    Orange
1    Banana
2     Grape
Name: fruits, dtype: object

In [37]:
df

   calories  fruits
0       420  Orange
1       380  Banana
2       390   Grape

In [38]:
# Locate Row
df.loc[0]

calories       420
fruits      Orange
Name: 0, dtype: object

In [41]:
df.loc[2]

calories      390
fruits      Grape
Name: 2, dtype: object

In [42]:
type(df)

pandas.core.frame.DataFrame

In [43]:
type(df['fruits'])

pandas.core.series.Series

In [44]:
type(df.loc[1])

pandas.core.series.Series

In [45]:
df.loc[[0,2]]

   calories  fruits
0       420  Orange
2       390   Grape

In [46]:
df.loc[[2,1]]

   calories  fruits
2       390   Grape
1       380  Banana

In [49]:
df2 = DataFrame({
    'state' : ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
    'year': [2000, 2001, 2002, 2001 , 2002,2003 ],
    'pop' : [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
})

df2

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [50]:
df2.head()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [51]:
df2.tail()

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [52]:
df3 = DataFrame(df2, columns=['year', 'state', 'pop'])
df3

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [53]:
df4 = DataFrame({
    'state' : ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
    'year': [2000, 2001, 2002, 2001 , 2002,2003 ],
    'pop' : [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}, columns=['year', 'state', 'pop'],
               index=['one', 'two', 'three', 'four', 'five', 'six'])
df4

       year   state  pop
one    2000    Ohio  1.5
two    2001    Ohio  1.7
three  2002    Ohio  3.6
four   2001  Nevada  2.4
five   2002  Nevada  2.9
six    2003  Nevada  3.2

In [54]:
df4.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [55]:
df4.columns

Index(['year', 'state', 'pop'], dtype='object')

In [56]:
df4['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [57]:
df4['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [58]:
df4[['state', 'pop']]

        state  pop
one      Ohio  1.5
two      Ohio  1.7
three    Ohio  3.6
four   Nevada  2.4
five   Nevada  2.9
six    Nevada  3.2

In [59]:
df4['year']

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [60]:
df4.loc['three']

year     2002
state    Ohio
pop       3.6
Name: three, dtype: object

In [62]:
df4.loc[['two', 'four', 'three']]

       year   state  pop
two    2001    Ohio  1.7
four   2001  Nevada  2.4
three  2002    Ohio  3.6

In [63]:
df4

       year   state  pop
one    2000    Ohio  1.5
two    2001    Ohio  1.7
three  2002    Ohio  3.6
four   2001  Nevada  2.4
five   2002  Nevada  2.9
six    2003  Nevada  3.2

In [64]:
df4.iloc[0]

year     2000
state    Ohio
pop       1.5
Name: one, dtype: object

In [65]:
df4.iloc[[1,3,0]]

      year   state  pop
two   2001    Ohio  1.7
four  2001  Nevada  2.4
one   2000    Ohio  1.5

In [66]:
df4.iloc[:3]

       year state  pop
one    2000  Ohio  1.5
two    2001  Ohio  1.7
three  2002  Ohio  3.6

In [67]:
# add a new column
df4['debt'] = 10
df4

       year   state  pop  debt
one    2000    Ohio  1.5    10
two    2001    Ohio  1.7    10
three  2002    Ohio  3.6    10
four   2001  Nevada  2.4    10
five   2002  Nevada  2.9    10
six    2003  Nevada  3.2    10

In [68]:
len(df4['debt'])

6

In [69]:
df4['debt'] = random(6) * 10
df4

       year   state  pop      debt
one    2000    Ohio  1.5  4.202965
two    2001    Ohio  1.7  1.777325
three  2002    Ohio  3.6  2.139418
four   2001  Nevada  2.4  6.705477
five   2002  Nevada  2.9  6.393136
six    2003  Nevada  3.2  1.413750

In [70]:
df4['debt'] = randn(len(df4['debt'])) * 10
df4

       year   state  pop       debt
one    2000    Ohio  1.5   2.486098
two    2001    Ohio  1.7 -14.958002
three  2002    Ohio  3.6   9.106034
four   2001  Nevada  2.4  23.121009
five   2002  Nevada  2.9  -3.376719
six    2003  Nevada  3.2   0.211748

In [71]:
df4['eastren'] = df4['state'] == 'Ohio'
df4

       year   state  pop       debt  eastren
one    2000    Ohio  1.5   2.486098     True
two    2001    Ohio  1.7 -14.958002     True
three  2002    Ohio  3.6   9.106034     True
four   2001  Nevada  2.4  23.121009    False
five   2002  Nevada  2.9  -3.376719    False
six    2003  Nevada  3.2   0.211748    False

In [72]:
df4[df4['pop'] > 2]

       year   state  pop       debt  eastren
three  2002    Ohio  3.6   9.106034     True
four   2001  Nevada  2.4  23.121009    False
five   2002  Nevada  2.9  -3.376719    False
six    2003  Nevada  3.2   0.211748    False

In [73]:
df4[df4['state'] == 'Nevada']

      year   state  pop       debt  eastren
four  2001  Nevada  2.4  23.121009    False
five  2002  Nevada  2.9  -3.376719    False
six   2003  Nevada  3.2   0.211748    False

In [74]:
df4.T

            one     two    three    four     five       six
year       2000    2001     2002    2001     2002      2003
state      Ohio    Ohio     Ohio  Nevada   Nevada    Nevada
pop         1.5     1.7      3.6     2.4      2.9       3.2
debt     2.4861 -14.958  9.10603  23.121 -3.37672  0.211748
eastren    True    True     True   False    False     False

In [75]:
df4['pop'][:2]

one    1.5
two    1.7
Name: pop, dtype: float64

In [76]:
df4[['pop'][-2:]]

       pop
one    1.5
two    1.7
three  3.6
four   2.4
five   2.9
six    3.2

In [77]:
df4['pop'][-2:]

five    2.9
six     3.2
Name: pop, dtype: float64