# Wilhelm Lange
## Week12: 04/16/2026 - 04/21/2026
### Python - Pandas DataFrame Processing

In [3]:
import numpy as np
import pandas as pd
from numpy.random import *
from pandas import *

In [4]:
#Drop Entries
df = DataFrame(np.arange(1,17).reshape((4,4)),
              columns=['one', 'two','three', 'four'],
              index=['Ohio', 'Colorado', 'Utah', 'New York'])
df

          one  two  three  four
Ohio        1    2      3     4
Colorado    5    6      7     8
Utah        9   10     11    12
New York   13   14     15    16

In [5]:
df.index

Index(['Ohio', 'Colorado', 'Utah', 'New York'], dtype='object')

In [6]:
df.index.name

In [7]:
df.drop(['Colorado'])

          one  two  three  four
Ohio        1    2      3     4
Utah        9   10     11    12
New York   13   14     15    16

In [8]:
df.drop(['Utah', 'Ohio'])

          one  two  three  four
Colorado    5    6      7     8
New York   13   14     15    16

In [9]:
df

          one  two  three  four
Ohio        1    2      3     4
Colorado    5    6      7     8
Utah        9   10     11    12
New York   13   14     15    16

In [10]:
df.drop(['three'], axis='columns')

          one  two  four
Ohio        1    2     4
Colorado    5    6     8
Utah        9   10    12
New York   13   14    16

In [11]:
df.drop(['three'], axis=1)

          one  two  four
Ohio        1    2     4
Colorado    5    6     8
Utah        9   10    12
New York   13   14    16

In [12]:
df.drop(['three', 'one'], axis=1)

          two  four
Ohio        2     4
Colorado    6     8
Utah       10    12
New York   14    16

In [13]:
df1 = df.copy()
df1

          one  two  three  four
Ohio        1    2      3     4
Colorado    5    6      7     8
Utah        9   10     11    12
New York   13   14     15    16

In [14]:
df.drop(['three', 'one'], axis=1, inplace=True)

In [15]:
df

          two  four
Ohio        2     4
Colorado    6     8
Utah       10    12
New York   14    16

In [16]:
df1[df1['three'] >= 7]

          one  two  three  four
Colorado    5    6      7     8
Utah        9   10     11    12
New York   13   14     15    16

In [17]:
# Data alignment
df1 = DataFrame(np.arange(9).reshape(3,3), columns=list('bcd'),
               index=['Ohio', 'Texas', 'Colorado'])

df2 = DataFrame(np.arange(12).reshape(4,3), columns=list('bde'),
               index=[ 'Utah','Ohio', 'Texas', 'Oregon'])

In [18]:
df1

          b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [19]:
df1 + df2

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [20]:
df1.add(df2)

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [21]:
df1

          b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [22]:
df2

        b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [23]:
df1.add(df2, fill_value=0) # number + 0 instead of (number + nan = nan)

            b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

In [24]:
df1['e'] = df1['b'] + df1['d']
df1

          b  c  d   e
Ohio      0  1  2   2
Texas     3  4  5   8
Colorado  6  7  8  14

In [25]:
#sort and rank
df = DataFrame(np.random.choice(np.arange(1,21), size=8).reshape(2,4),
              columns=list('dabd'),
              index=['three', 'one'])
df

        d   a   b   d
three  11  12   5  13
one    18  15  19   8

In [26]:
df.sort_index()

        d   a   b   d
one    18  15  19   8
three  11  12   5  13

In [27]:
df.sort_index(axis=1)

        a   b   d   d
three  12   5  11  13
one    15  19  18   8

In [28]:
df

        d   a   b   d
three  11  12   5  13
one    18  15  19   8

In [29]:
df.sort_index(axis=1, ascending=False)

        d   d   b   a
three  11  13   5  12
one    18   8  19  15

In [30]:
# Sort by values
df.sort_values(by='b')

        d   a   b   d
three  11  12   5  13
one    18  15  19   8

In [31]:
df.sort_values(by='d')

ValueError: The column label 'd' is not unique.

In [ ]:
df = DataFrame(np.random.choice(np.arange(-10,20), size=16).reshape(4,4),
              columns=list('dabc'),
              index=['three', 'one', 'four', 'seven'])
df

In [ ]:
df.sort_values(by='c')

In [ ]:
df.sort_values(by=['a', 'd'])

In [ ]:
df.sort_values(by='seven', axis = 1)

In [ ]:
df.sort_values(by=['one','seven'], axis = 1)

In [ ]:
df.sort_values(by=['one','seven'], axis = 1, inplace=True)

In [ ]:
df

In [ ]:
# Ranking
df.rank()

In [ ]:
df.rank().astype(int)

In [ ]:
df.values

In [ ]:
# Statistics
df

In [ ]:
df['e'] = np.where(df['a'] > 2, df['c'], np.nan)

In [ ]:
df

In [ ]:
df.sum()

In [ ]:
df.sum(axis=1)

In [ ]:
df.mean()

In [ ]:
df.mean(axis='columns')

In [ ]:
df.values

In [ ]:
df.mean(axis=1, skipna=False)

In [ ]:
df.min()

In [ ]:
df.min(axis=1)

In [ ]:
df.max(axis=1)

In [32]:
# idxmax() returns the index of the first occurrence of the maximum over the requested axis
df = DataFrame([np.random.choice(np.arange(-5,5), size=5), np.random.choice(np.arange(-5,5), size=5),np.random.choice(np.arange(-5,5), size=5),np.random.choice(np.arange(-5,5), size=5)]
              ,index=list('abcd'),
              columns=['one','two','three','four','five'])
df

   one  two  three  four  five
a   -3    1      0    -5     0
b    2   -4     -5     3     0
c    1    1      2    -1     2
d    3   -3     -3    -3     2

In [33]:
df

   one  two  three  four  five
a   -3    1      0    -5     0
b    2   -4     -5     3     0
c    1    1      2    -1     2
d    3   -3     -3    -3     2

In [34]:
df.idxmax()

one      d
two      a
three    c
four     b
five     c
dtype: object

In [35]:
df.idxmin()

one      a
two      b
three    b
four     a
five     a
dtype: object

In [36]:
df.idxmin(axis=1)

a     four
b    three
c     four
d      two
dtype: object

In [37]:
df

   one  two  three  four  five
a   -3    1      0    -5     0
b    2   -4     -5     3     0
c    1    1      2    -1     2
d    3   -3     -3    -3     2

In [41]:
# Create a Dataframe representing stock prices
data = {
    'Date': pd.date_range(start='2026-01-01', end='2026-01-10'),
    'META': np.random.choice(np.arange(100,300), size=10),
    'TSLA': np.random.choice(np.arange(100,300), size=10),
    'GOOGL': np.random.choice(np.arange(100,300), size=10),
}
data

{'Date': DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
                '2026-01-05', '2026-01-06', '2026-01-07', '2026-01-08',
                '2026-01-09', '2026-01-10'],
               dtype='datetime64[ns]', freq='D'),
 'META': array([132, 282, 290, 107, 292, 139, 115, 286, 117, 216]),
 'TSLA': array([193, 274, 189, 220, 136, 182, 273, 247, 164, 245]),
 'GOOGL': array([215, 298, 225, 235, 292, 265, 179, 268, 269, 147])}

In [40]:
df = DataFrame(data, index=data['Date'], columns=['Meta', 'TSLA', 'GOOGL'])
df

           Meta  TSLA  GOOGL
2026-01-01  NaN   219    163
2026-01-02  NaN   219    102
2026-01-03  NaN   216    239
2026-01-04  NaN   272    185
2026-01-05  NaN   254    233
2026-01-06  NaN   287    105
2026-01-07  NaN   282    271
2026-01-08  NaN   194    208
2026-01-09  NaN   297    139
2026-01-10  NaN   108    295

In [42]:
df.index.name = 'Date'

In [43]:
# Find the date with th highest closing price for each stock 
df.idxmax()

TypeError: reduction operation 'argmax' not allowed for this dtype

In [44]:
df.idxmin()

TypeError: reduction operation 'argmin' not allowed for this dtype

In [45]:
df_t = df.T
df_t

Date,2026-01-01,2026-01-02,2026-01-03,2026-01-04,2026-01-05,2026-01-06,2026-01-07,2026-01-08,2026-01-09,2026-01-10
Meta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TSLA,219,219,216,272,254,287,282,194,297,108
GOOGL,163,102,239,185,233,105,271,208,139,295

In [46]:
# Find the stock with the minumum and maimum calues for a specific date: "2026-01-02"
df_t['2026-01-02'].idxmax()

TypeError: reduction operation 'argmax' not allowed for this dtype

In [47]:
df_t['2026-01-02'].idxmax()

TypeError: reduction operation 'argmax' not allowed for this dtype

In [48]:
df.loc['2026-01-02'].idxmax()

TypeError: reduction operation 'argmax' not allowed for this dtype

In [49]:
# Missing data
sample = np.append(np.arange(1,6),[np.nan,np.nan])

df = DataFrame([np.random.choice(sample, size=5), np.random.choice(sample),size=5), np.random.choice(sample),size=5), np.random.choice(sample),size=5), np.random.choice(sample),size=5),
               index=list('abcd'),
               columns=['one','two','three','four','five']])
df

SyntaxError: invalid syntax (<ipython-input-49-97fbad70915b>, line 4)

In [50]:
df.drop

<bound method DataFrame.drop of            Meta  TSLA  GOOGL
Date
2026-01-01  NaN   219    163
2026-01-02  NaN   219    102
2026-01-03  NaN   216    239
2026-01-04  NaN   272    185
2026-01-05  NaN   254    233
2026-01-06  NaN   287    105
2026-01-07  NaN   282    271
2026-01-08  NaN   194    208
2026-01-09  NaN   297    139
2026-01-10  NaN   108    295>

In [51]:
#using thresh to keep only rows having 2 or more valid data
df.dropna(thresh=4)

Empty DataFrame
Columns: [Meta, TSLA, GOOGL]
Index: []

In [52]:
# address nan values
df.fillna(0)

            Meta  TSLA  GOOGL
Date
2026-01-01     0   219    163
2026-01-02     0   219    102
2026-01-03     0   216    239
2026-01-04     0   272    185
2026-01-05     0   254    233
2026-01-06     0   287    105
2026-01-07     0   282    271
2026-01-08     0   194    208
2026-01-09     0   297    139
2026-01-10     0   108    295

In [53]:
df.ffil()

AttributeError: 'DataFrame' object has no attribute 'ffil'

In [54]:
df.fillna(df.mean())

            Meta  TSLA  GOOGL
Date
2026-01-01   NaN   219    163
2026-01-02   NaN   219    102
2026-01-03   NaN   216    239
2026-01-04   NaN   272    185
2026-01-05   NaN   254    233
2026-01-06   NaN   287    105
2026-01-07   NaN   282    271
2026-01-08   NaN   194    208
2026-01-09   NaN   297    139
2026-01-10   NaN   108    295

In [55]:
df.fillna(df.max(), axis=1)

NotImplementedError: Currently only can fill with dict/Series column by column

In [56]:
df.fillna(df.max())

            Meta  TSLA  GOOGL
Date
2026-01-01   NaN   219    163
2026-01-02   NaN   219    102
2026-01-03   NaN   216    239
2026-01-04   NaN   272    185
2026-01-05   NaN   254    233
2026-01-06   NaN   287    105
2026-01-07   NaN   282    271
2026-01-08   NaN   194    208
2026-01-09   NaN   297    139
2026-01-10   NaN   108    295

In [58]:
df.fillna(df.max(), inplace=True)

In [59]:
df

            Meta  TSLA  GOOGL
Date
2026-01-01   NaN   219    163
2026-01-02   NaN   219    102
2026-01-03   NaN   216    239
2026-01-04   NaN   272    185
2026-01-05   NaN   254    233
2026-01-06   NaN   287    105
2026-01-07   NaN   282    271
2026-01-08   NaN   194    208
2026-01-09   NaN   297    139
2026-01-10   NaN   108    295

In [60]:
data = {
    'CustomerID': [1001, 1002,1003,1004],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25,30,None,22],
    'Income': [50000, None, 70000, 60000]
}

df = DataFrame(data)
df

   CustomerID     Name   Age   Income
0        1001    Alice  25.0  50000.0
1        1002      Bob  30.0      NaN
2        1003  Charlie   NaN  70000.0
3        1004    David  22.0  60000.0

In [61]:
df = df.set_index('CustomerID')
df

               Name   Age   Income
CustomerID
1001          Alice  25.0  50000.0
1002            Bob  30.0      NaN
1003        Charlie   NaN  70000.0
1004          David  22.0  60000.0

In [62]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
df['Age'] = df['Age'].astype(int)
df

               Name  Age   Income
CustomerID
1001          Alice   25  50000.0
1002            Bob   30      NaN
1003        Charlie   25  70000.0
1004          David   22  60000.0